### ISSUE TITLE
Stop sending any emails to my email address

### ISSUE THREAD

**Issue by pipboy96** [FleekHQ/fleek-docs#10]
I have asked to stop sending any emails to my public GitHub email address, but I got another message:

![image](https://user-images.githubusercontent.com/46632672/79370069-b6dde100-7f5a-11ea-936a-0ba9711054e9.png)

For your information, this goes against [CAN-SPAM Act](https://en.wikipedia.org/wiki/CAN-SPAM_Act_of_2003) and GDPR.

Further email messages will be reported to the police.

Kind regards.

**Comment by Blockchainbrett** [comment]
Hey @pipboy96 sorry about that. There's an unsubscribe link in the email you can click to exclude yourself from all future emails. I will triple-check that you are already excluded from any marketing emails.
