### ISSUE TITLE
Stop spamming public GitHub emails, please.

### ISSUE THREAD

**Issue by pipboy96** [FleekHQ/fleek-docs#7]
Can you, you know, STOP SENDING SPAM? I got three emails from you. Even if I were interested in using your product in the first place (no), now I am completely not interested. I reported you to Gmail and GitHub support. Stop doing that, you are harming your own business and NOT helping it.

**Comment by pipboy96** [comment]
@Blockchainbrett Have you unsubscribed me from all emails?

**Comment by Blockchainbrett** [comment]
Yes, you're unsubscribed. Thanks.
